In [1]:
# Import necessary libraries
import numpy as np
import pandas as pd
# Create the dataset
data = {
    'Email Length': [50, 200, 30, 150, 80, 300, 60, 250],
    'Has Links': [1, 1, 0, 1, 0, 1, 0, 1],
    'Has Exclamation Marks': [0, 1, 0, 1, 0, 1, 1, 1],
    'Has Dollar Signs': [0, 1, 0, 0, 0, 1, 0, 0],
    'Contains "Buy"': [0, 1, 0, 1, 0, 1, 0, 1],
    'Spam': [0, 1, 0, 1, 0, 1, 0, 1]
}

# Convert to a DataFrame
df = pd.DataFrame(data)
df.head(8)
from sklearn.model_selection import train_test_split
# Split data into features (X) and target (y)
X = df[['Email Length', 'Has Links', 'Has Exclamation Marks', 'Has Dollar Signs', 'Contains "Buy"']]
y = df['Spam']

# Step 1: Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
from sklearn.linear_model import LogisticRegression

# Step 2: Create the Logistic Regression model
model = LogisticRegression()

# Step 3: Train the model
model.fit(X_train, y_train)
print(model)
# Step 4: Make predictions on the test set
y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Step 5: Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Optional: Predict probabilities
y_pred_proba = model.predict_proba(X_test)
print("Predicted Probabilities:")
print(y_pred_proba)

LogisticRegression()
Accuracy: 1.0
Confusion Matrix:
[[1 0]
 [0 2]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         2

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

Predicted Probabilities:
[[4.45955395e-07 9.99999554e-01]
 [1.48769885e-14 1.00000000e+00]
 [9.99986445e-01 1.35551958e-05]]


In [2]:
# Print model details
print("Model Details:")
print(f"Intercept (Bias): {model.intercept_[0]}")
print(f"Coefficients: {model.coef_[0]}")

Model Details:
Intercept (Bias): -19.820151024789116
Coefficients: [0.17217975 0.00243621 0.0023741  0.         0.00243621]


In [3]:
# Import necessary libraries
import numpy as np
import pandas as pd

In [4]:
# Create the dataset
data = {
    'Email Length': [50, 200, 30, 150, 80, 300, 60, 250],
    'Has Links': [1, 1, 0, 1, 0, 1, 0, 1],
    'Has Exclamation Marks': [0, 1, 0, 1, 0, 1, 1, 1],
    'Has Dollar Signs': [0, 1, 0, 0, 0, 1, 0, 0],
    'Contains "Buy"': [0, 1, 0, 1, 0, 1, 0, 1],
    'Spam': [0, 1, 0, 1, 0, 1, 0, 1]
}

# Convert to a DataFrame
df = pd.DataFrame(data)
df.head()

Email Length  Has Links  Has Exclamation Marks  Has Dollar Signs  \
0            50          1                      0                 0   
1           200          1                      1                 1   
2            30          0                      0                 0   
3           150          1                      1                 0   
4            80          0                      0                 0   

   Contains "Buy"  Spam  
0               0     0  
1               1     1  
2               0     0  
3               1     1  
4               0     0

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
df.head(8)

Email Length  Has Links  Has Exclamation Marks  Has Dollar Signs  \
0            50          1                      0                 0   
1           200          1                      1                 1   
2            30          0                      0                 0   
3           150          1                      1                 0   
4            80          0                      0                 0   
5           300          1                      1                 1   
6            60          0                      1                 0   
7           250          1                      1                 0   

   Contains "Buy"  Spam  
0               0     0  
1               1     1  
2               0     0  
3               1     1  
4               0     0  
5               1     1  
6               0     0  
7               1     1

In [7]:
# Split data into features (X) and target (y)
X = df[['Email Length', 'Has Links', 'Has Exclamation Marks', 'Has Dollar Signs', 'Contains "Buy"']]
y = df['Spam']

# Step 1: Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [8]:
X_train

Email Length  Has Links  Has Exclamation Marks  Has Dollar Signs  \
7           250          1                      1                 0   
2            30          0                      0                 0   
4            80          0                      0                 0   
3           150          1                      1                 0   
6            60          0                      1                 0   

   Contains "Buy"  
7               1  
2               0  
4               0  
3               1  
6               0

In [9]:
X_test

Email Length  Has Links  Has Exclamation Marks  Has Dollar Signs  \
1           200          1                      1                 1   
5           300          1                      1                 1   
0            50          1                      0                 0   

   Contains "Buy"  
1               1  
5               1  
0               0

In [10]:
y_train

7    1
2    0
4    0
3    1
6    0
Name: Spam, dtype: int64

In [11]:
y_test

1    1
5    1
0    0
Name: Spam, dtype: int64

In [12]:
from sklearn.linear_model import LogisticRegression

In [13]:
# Step 2: Create the Logistic Regression model
model = LogisticRegression()

# Step 3: Train the model
model.fit(X_train, y_train)

# Step 4: Make predictions on the test set
y_pred = model.predict(X_test)


In [14]:
# Print model details
print("Model Details:")
print(f"Intercept (Bias): {model.intercept_[0]}")
print(f"Coefficients: {model.coef_[0]}")

Model Details:
Intercept (Bias): -19.820151024789116
Coefficients: [0.17217975 0.00243621 0.0023741  0.         0.00243621]


In [15]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [16]:
# Step 5: Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Optional: Predict probabilities
y_pred_proba = model.predict_proba(X_test)
print("Predicted Probabilities:")
print(y_pred_proba)


Accuracy: 1.0
Confusion Matrix:
[[1 0]
 [0 2]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         2

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

Predicted Probabilities:
[[4.45955395e-07 9.99999554e-01]
 [1.48769885e-14 1.00000000e+00]
 [9.99986445e-01 1.35551958e-05]]
